//! Raw bindings to the CyberRemesher C ABI.
//!
//! Generated by `bindgen` from `capi/include/cyber_capi.h` and nothing else.
//! There are no hand-written declarations here, for the reason `claycore-sys`
//! has none: a declaration written twice is a declaration that can disagree
//! with itself, and the disagreement is a memory-safety bug rather than a
//! compile error.
//!
//! Everything here is `unsafe`. The safe surface is `cyberremesh`, which is
//! the only other crate in this workspace permitted `unsafe` and is where the
//! ownership rules live.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
