//! Raw FFI bindings to the ClayCore C ABI.
//!
//! Everything below the module docs is generated by `bindgen` from
//! `vendor/ClayCore/bindings/c/clay.h` at build time. There are no
//! hand-written declarations here by design: a signature change in the pinned
//! engine must surface as a compile error in the safe wrapper, not as a
//! mismatch at runtime.
//!
//! Do not use this crate directly. Use `claycore`, which is the only crate
//! permitted to call it.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// Accelerated backends compiled into this build, comma-separated.
///
/// This is what the build selected, which is not the same question as what the
/// engine registers at runtime — a backend can be compiled in and still fail
/// to register on a machine whose driver is unavailable. Ask the engine for
/// the runtime answer.
pub const COMPILED_BACKENDS: &str = env!("CLAYCORE_COMPILED_BACKENDS");
