#!/usr/bin/env python3
"""Generates the attribution manifest from what actually ships.

The licence policy in `deny.toml` says the application is distributed as a
binary with an attribution manifest. This writes that manifest, from
`cargo metadata` rather than from a hand-kept list — a list maintained by hand
is one that is wrong the first time a transitive dependency moves.

Run with `--check` in CI to fail when the committed file no longer matches.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "ATTRIBUTION.md"

# The targets `deny.toml` audits. Anything outside them is not shipped, so
# listing it would overstate what the binary contains.
TARGETS = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
]


def workspace_members(metadata: dict) -> set[str]:
    return set(metadata.get("workspace_members", []))


def third_party(metadata: dict) -> list[dict]:
    """Every package that is not ours, deduplicated by name and version."""
    ours = workspace_members(metadata)
    seen: dict[tuple[str, str], dict] = {}
    for package in metadata["packages"]:
        if package["id"] in ours:
            continue
        key = (package["name"], package["version"])
        seen[key] = package
    return [seen[key] for key in sorted(seen)]


def render(packages: list[dict], engine_licence: str) -> str:
    lines = [
        "# Attribution",
        "",
        "Everything this application is built from, and the terms it comes",
        "under. Generated by `tools/attribution.py` from `cargo metadata`, so it",
        "cannot drift from what is actually linked — a hand-kept list is wrong",
        "the first time a transitive dependency moves.",
        "",
        "Regenerate with:",
        "",
        "```sh",
        "python3 tools/attribution.py",
        "```",
        "",
        "## The engine",
        "",
        "ClayCore is vendored as a git submodule under `vendor/ClayCore` and",
        "linked statically. Its licence is reproduced in full at",
        "`vendor/ClayCore/LICENSE`.",
        "",
        f"- **ClayCore** — {engine_licence}",
        "",
        f"## Rust dependencies ({len(packages)})",
        "",
        "| Package | Version | Licence |",
        "|---|---|---|",
    ]
    for package in packages:
        licence = package.get("license") or package.get("license_file") or "see repository"
        lines.append(f"| {package['name']} | {package['version']} | {licence} |")
    lines.append("")
    return "\n".join(lines)


def engine_licence() -> str:
    path = ROOT / "vendor" / "ClayCore" / "LICENSE"
    if not path.is_file():
        return "see vendor/ClayCore/LICENSE"
    first = path.read_text(encoding="utf-8", errors="replace").strip().splitlines()
    return first[0].strip() if first else "see vendor/ClayCore/LICENSE"


def collect() -> str:
    packages: dict[tuple[str, str], dict] = {}
    for target in TARGETS:
        result = subprocess.run(
            [
                "cargo",
                "metadata",
                "--format-version",
                "1",
                "--filter-platform",
                target,
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print(result.stderr, file=sys.stderr)
            raise SystemExit(f"cargo metadata failed for {target}")
        metadata = json.loads(result.stdout)
        for package in third_party(metadata):
            packages[(package["name"], package["version"])] = package
    ordered = [packages[key] for key in sorted(packages)]
    return render(ordered, engine_licence())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed manifest is out of date",
    )
    args = parser.parse_args()

    rendered = collect()
    if args.check:
        current = MANIFEST.read_text(encoding="utf-8") if MANIFEST.is_file() else ""
        if current != rendered:
            print(
                "ATTRIBUTION.md is out of date. Run: python3 tools/attribution.py",
                file=sys.stderr,
            )
            return 1
        print(f"Attribution manifest is current ({rendered.count('|') // 3} entries).")
        return 0

    MANIFEST.write_text(rendered, encoding="utf-8")
    print(f"Wrote {MANIFEST.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
