#!/usr/bin/env python3
"""Generates the attribution manifest from what actually ships.

The licence policy in `deny.toml` says the application is distributed as a
binary with an attribution manifest. This writes that manifest, from
`cargo metadata` rather than from a hand-kept list — a list maintained by hand
is one that is wrong the first time a transitive dependency moves.

Run with `--check` in CI to fail when the committed file no longer matches.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "ATTRIBUTION.md"

# Deliberately NOT filtered by platform.
#
# The first version took the union over the four targets `deny.toml` audits,
# to avoid crediting crates the binary does not contain. That produced a
# different manifest on macOS than on Linux, and CI caught it: `cargo metadata
# --filter-platform` filters the *target* graph, but build-dependencies are
# resolved for the HOST — so the proc-macro and build-script tree differs by
# whoever ran it. 197 packages here, 263 on a Linux runner.
#
# The whole resolved graph is a pure function of Cargo.toml and the committed
# Cargo.lock, so it is the same everywhere. It overstates: it includes crates
# that only build on platforms this application does not ship to. Crediting a
# project whose code is not in the binary is harmless; omitting one whose code
# is, is not — and a manifest that depends on who generated it cannot be
# checked in CI at all, which is worth more than the precision.


def workspace_members(metadata: dict) -> set[str]:
    return set(metadata.get("workspace_members", []))


def third_party(metadata: dict) -> list[dict]:
    """Every package that is not ours, deduplicated by name and version."""
    ours = workspace_members(metadata)
    seen: dict[tuple[str, str], dict] = {}
    for package in metadata["packages"]:
        if package["id"] in ours:
            continue
        key = (package["name"], package["version"])
        seen[key] = package
    return [seen[key] for key in sorted(seen)]


def render(packages: list[dict], engine_licence: str) -> str:
    lines = [
        "# Attribution",
        "",
        "Everything this application is built from, and the terms it comes",
        "under. Generated by `tools/attribution.py` from `cargo metadata`, so it",
        "cannot drift from what is actually linked — a hand-kept list is wrong",
        "the first time a transitive dependency moves.",
        "",
        "This is the whole resolved dependency graph, not the subset that",
        "reaches any one platform's binary. It is therefore a pure function of",
        "`Cargo.lock` and identical on every machine, which is what lets CI",
        "check it. Some entries build only on platforms this application does",
        "not ship to.",
        "",
        "Regenerate with:",
        "",
        "```sh",
        "python3 tools/attribution.py",
        "```",
        "",
        "## The engine",
        "",
        "ClayCore is vendored as a git submodule under `vendor/ClayCore` and",
        "linked statically. Its licence is reproduced in full at",
        "`vendor/ClayCore/LICENSE`.",
        "",
        f"- **ClayCore** — {engine_licence}",
        "",
        f"## Rust dependencies ({len(packages)})",
        "",
        "| Package | Version | Licence |",
        "|---|---|---|",
    ]
    for package in packages:
        licence = package.get("license") or package.get("license_file") or "see repository"
        lines.append(f"| {package['name']} | {package['version']} | {licence} |")
    lines.append("")
    return "\n".join(lines)


def engine_licence() -> str:
    path = ROOT / "vendor" / "ClayCore" / "LICENSE"
    if not path.is_file():
        return "see vendor/ClayCore/LICENSE"
    first = path.read_text(encoding="utf-8", errors="replace").strip().splitlines()
    return first[0].strip() if first else "see vendor/ClayCore/LICENSE"


def collect() -> str:
    result = subprocess.run(
        ["cargo", "metadata", "--format-version", "1"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        raise SystemExit("cargo metadata failed")
    metadata = json.loads(result.stdout)
    packages = {(p["name"], p["version"]): p for p in third_party(metadata)}
    ordered = [packages[key] for key in sorted(packages)]
    return render(ordered, engine_licence())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed manifest is out of date",
    )
    args = parser.parse_args()

    rendered = collect()
    if args.check:
        current = MANIFEST.read_text(encoding="utf-8") if MANIFEST.is_file() else ""
        if current != rendered:
            print(
                "ATTRIBUTION.md is out of date. Run: python3 tools/attribution.py",
                file=sys.stderr,
            )
            # The difference, not just its existence. This check first failed
            # for a reason no local run could reproduce — the manifest was
            # host-dependent — and "it differs" sent me guessing instead of
            # looking.
            import difflib

            diff = difflib.unified_diff(
                current.splitlines(),
                rendered.splitlines(),
                fromfile="committed",
                tofile="generated here",
                lineterm="",
                n=1,
            )
            for line in list(diff)[:60]:
                print(line, file=sys.stderr)
            return 1
        print(f"Attribution manifest is current ({rendered.count('|') // 3} entries).")
        return 0

    MANIFEST.write_text(rendered, encoding="utf-8")
    print(f"Wrote {MANIFEST.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
